// flow-typed signature: 06b7a1904e6767e438cb0d5764b0f22a
// flow-typed version: <<STUB>>/aurelia-animator-css_v^1.0.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurelia-animator-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurelia-animator-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurelia-animator-css/build/args' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/babel-options' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/paths' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/tasks/build' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/tasks/clean' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/tasks/dev' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/tasks/doc' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/tasks/lint' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/tasks/prepare-release' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/tasks/test' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/build/typescript-options' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/config' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/amd/aurelia-animator-css' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/amd/index' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/aurelia-animator-css' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/commonjs/aurelia-animator-css' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/es2015/aurelia-animator-css' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/es2015/index' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/native-modules/aurelia-animator-css' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/native-modules/index' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/system/aurelia-animator-css' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/dist/system/index' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/gulpfile' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/karma.conf' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/src/animator' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/src/index' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/test/animate.spec' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/test/animator.spec' {
  declare module.exports: any;
}

declare module 'aurelia-animator-css/test/run-sequence.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurelia-animator-css/build/args.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/args'>;
}
declare module 'aurelia-animator-css/build/babel-options.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/babel-options'>;
}
declare module 'aurelia-animator-css/build/paths.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/paths'>;
}
declare module 'aurelia-animator-css/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify'>;
}
declare module 'aurelia-animator-css/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter'>;
}
declare module 'aurelia-animator-css/build/tasks/build.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/tasks/build'>;
}
declare module 'aurelia-animator-css/build/tasks/clean.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/tasks/clean'>;
}
declare module 'aurelia-animator-css/build/tasks/dev.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/tasks/dev'>;
}
declare module 'aurelia-animator-css/build/tasks/doc.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/tasks/doc'>;
}
declare module 'aurelia-animator-css/build/tasks/lint.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/tasks/lint'>;
}
declare module 'aurelia-animator-css/build/tasks/prepare-release.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/tasks/prepare-release'>;
}
declare module 'aurelia-animator-css/build/tasks/test.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/tasks/test'>;
}
declare module 'aurelia-animator-css/build/typescript-options.js' {
  declare module.exports: $Exports<'aurelia-animator-css/build/typescript-options'>;
}
declare module 'aurelia-animator-css/config.js' {
  declare module.exports: $Exports<'aurelia-animator-css/config'>;
}
declare module 'aurelia-animator-css/dist/amd/aurelia-animator-css.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/amd/aurelia-animator-css'>;
}
declare module 'aurelia-animator-css/dist/amd/index.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/amd/index'>;
}
declare module 'aurelia-animator-css/dist/aurelia-animator-css.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/aurelia-animator-css'>;
}
declare module 'aurelia-animator-css/dist/commonjs/aurelia-animator-css.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/commonjs/aurelia-animator-css'>;
}
declare module 'aurelia-animator-css/dist/commonjs/index.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/commonjs/index'>;
}
declare module 'aurelia-animator-css/dist/es2015/aurelia-animator-css.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/es2015/aurelia-animator-css'>;
}
declare module 'aurelia-animator-css/dist/es2015/index.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/es2015/index'>;
}
declare module 'aurelia-animator-css/dist/native-modules/aurelia-animator-css.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/native-modules/aurelia-animator-css'>;
}
declare module 'aurelia-animator-css/dist/native-modules/index.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/native-modules/index'>;
}
declare module 'aurelia-animator-css/dist/system/aurelia-animator-css.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/system/aurelia-animator-css'>;
}
declare module 'aurelia-animator-css/dist/system/index.js' {
  declare module.exports: $Exports<'aurelia-animator-css/dist/system/index'>;
}
declare module 'aurelia-animator-css/gulpfile.js' {
  declare module.exports: $Exports<'aurelia-animator-css/gulpfile'>;
}
declare module 'aurelia-animator-css/karma.conf.js' {
  declare module.exports: $Exports<'aurelia-animator-css/karma.conf'>;
}
declare module 'aurelia-animator-css/src/animator.js' {
  declare module.exports: $Exports<'aurelia-animator-css/src/animator'>;
}
declare module 'aurelia-animator-css/src/index.js' {
  declare module.exports: $Exports<'aurelia-animator-css/src/index'>;
}
declare module 'aurelia-animator-css/test/animate.spec.js' {
  declare module.exports: $Exports<'aurelia-animator-css/test/animate.spec'>;
}
declare module 'aurelia-animator-css/test/animator.spec.js' {
  declare module.exports: $Exports<'aurelia-animator-css/test/animator.spec'>;
}
declare module 'aurelia-animator-css/test/run-sequence.spec.js' {
  declare module.exports: $Exports<'aurelia-animator-css/test/run-sequence.spec'>;
}
