// flow-typed signature: dd418ea8a936fc0d7fe2b046e0adde6c
// flow-typed version: <<STUB>>/aurelia-tools_v^1.0.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurelia-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurelia-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurelia-tools/context-debugger/devtools' {
  declare module.exports: any;
}

declare module 'aurelia-tools/src/build' {
  declare module.exports: any;
}

declare module 'aurelia-tools/src/dev' {
  declare module.exports: any;
}

declare module 'aurelia-tools/src/doc' {
  declare module.exports: any;
}

declare module 'aurelia-tools/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurelia-tools/context-debugger/devtools.js' {
  declare module.exports: $Exports<'aurelia-tools/context-debugger/devtools'>;
}
declare module 'aurelia-tools/src/build.js' {
  declare module.exports: $Exports<'aurelia-tools/src/build'>;
}
declare module 'aurelia-tools/src/dev.js' {
  declare module.exports: $Exports<'aurelia-tools/src/dev'>;
}
declare module 'aurelia-tools/src/doc.js' {
  declare module.exports: $Exports<'aurelia-tools/src/doc'>;
}
declare module 'aurelia-tools/src/index.js' {
  declare module.exports: $Exports<'aurelia-tools/src/index'>;
}
