// flow-typed signature: 793be4c0ec5cca5d4edf69435ebacb89
// flow-typed version: <<STUB>>/aurelia-dialog_v^1.0.0-rc.1.0.3/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurelia-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurelia-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurelia-dialog/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/attach-focus' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/aurelia-dialog' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/dialog-cancel-error' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/dialog-configuration' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/dialog-controller' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/dialog-renderer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/dialog-result' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/dialog-service' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/dialog-settings' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/interfaces' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/lifecycle' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/renderer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/ux-dialog-body' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/ux-dialog-footer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/ux-dialog-header' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/amd/ux-dialog' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/attach-focus' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/aurelia-dialog' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/dialog-cancel-error' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/dialog-configuration' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/dialog-controller' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/dialog-renderer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/dialog-result' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/dialog-service' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/dialog-settings' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/interfaces' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/lifecycle' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/renderer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/ux-dialog-body' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/ux-dialog-footer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/ux-dialog-header' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/commonjs/ux-dialog' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/attach-focus' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/aurelia-dialog' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/dialog-cancel-error' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/dialog-configuration' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/dialog-controller' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/dialog-renderer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/dialog-result' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/dialog-service' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/dialog-settings' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/interfaces' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/lifecycle' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/renderer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/ux-dialog-body' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/ux-dialog-footer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/ux-dialog-header' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/es2015/ux-dialog' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/attach-focus' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/aurelia-dialog' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/dialog-cancel-error' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/dialog-configuration' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/dialog-controller' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/dialog-renderer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/dialog-result' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/dialog-service' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/dialog-settings' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/interfaces' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/lifecycle' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/renderer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/ux-dialog-body' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/ux-dialog-footer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/ux-dialog-header' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/native-modules/ux-dialog' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/attach-focus' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/aurelia-dialog' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/dialog-cancel-error' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/dialog-configuration' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/dialog-controller' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/dialog-renderer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/dialog-result' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/dialog-service' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/dialog-settings' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/interfaces' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/lifecycle' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/renderer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/ux-dialog-body' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/ux-dialog-footer' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/ux-dialog-header' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/dist/system/ux-dialog' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/doc/example/common-dialogs' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/doc/example/prompt' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/doc/shape-defs' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/doc/shape-doc' {
  declare module.exports: any;
}

declare module 'aurelia-dialog/karma.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurelia-dialog/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify.js' {
  declare module.exports: $Exports<'aurelia-dialog/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify'>;
}
declare module 'aurelia-dialog/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter.js' {
  declare module.exports: $Exports<'aurelia-dialog/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter'>;
}
declare module 'aurelia-dialog/dist/amd/attach-focus.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/attach-focus'>;
}
declare module 'aurelia-dialog/dist/amd/aurelia-dialog.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/aurelia-dialog'>;
}
declare module 'aurelia-dialog/dist/amd/dialog-cancel-error.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/dialog-cancel-error'>;
}
declare module 'aurelia-dialog/dist/amd/dialog-configuration.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/dialog-configuration'>;
}
declare module 'aurelia-dialog/dist/amd/dialog-controller.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/dialog-controller'>;
}
declare module 'aurelia-dialog/dist/amd/dialog-renderer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/dialog-renderer'>;
}
declare module 'aurelia-dialog/dist/amd/dialog-result.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/dialog-result'>;
}
declare module 'aurelia-dialog/dist/amd/dialog-service.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/dialog-service'>;
}
declare module 'aurelia-dialog/dist/amd/dialog-settings.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/dialog-settings'>;
}
declare module 'aurelia-dialog/dist/amd/interfaces.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/interfaces'>;
}
declare module 'aurelia-dialog/dist/amd/lifecycle.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/lifecycle'>;
}
declare module 'aurelia-dialog/dist/amd/renderer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/renderer'>;
}
declare module 'aurelia-dialog/dist/amd/ux-dialog-body.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/ux-dialog-body'>;
}
declare module 'aurelia-dialog/dist/amd/ux-dialog-footer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/ux-dialog-footer'>;
}
declare module 'aurelia-dialog/dist/amd/ux-dialog-header.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/ux-dialog-header'>;
}
declare module 'aurelia-dialog/dist/amd/ux-dialog.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/amd/ux-dialog'>;
}
declare module 'aurelia-dialog/dist/commonjs/attach-focus.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/attach-focus'>;
}
declare module 'aurelia-dialog/dist/commonjs/aurelia-dialog.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/aurelia-dialog'>;
}
declare module 'aurelia-dialog/dist/commonjs/dialog-cancel-error.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/dialog-cancel-error'>;
}
declare module 'aurelia-dialog/dist/commonjs/dialog-configuration.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/dialog-configuration'>;
}
declare module 'aurelia-dialog/dist/commonjs/dialog-controller.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/dialog-controller'>;
}
declare module 'aurelia-dialog/dist/commonjs/dialog-renderer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/dialog-renderer'>;
}
declare module 'aurelia-dialog/dist/commonjs/dialog-result.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/dialog-result'>;
}
declare module 'aurelia-dialog/dist/commonjs/dialog-service.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/dialog-service'>;
}
declare module 'aurelia-dialog/dist/commonjs/dialog-settings.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/dialog-settings'>;
}
declare module 'aurelia-dialog/dist/commonjs/interfaces.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/interfaces'>;
}
declare module 'aurelia-dialog/dist/commonjs/lifecycle.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/lifecycle'>;
}
declare module 'aurelia-dialog/dist/commonjs/renderer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/renderer'>;
}
declare module 'aurelia-dialog/dist/commonjs/ux-dialog-body.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/ux-dialog-body'>;
}
declare module 'aurelia-dialog/dist/commonjs/ux-dialog-footer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/ux-dialog-footer'>;
}
declare module 'aurelia-dialog/dist/commonjs/ux-dialog-header.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/ux-dialog-header'>;
}
declare module 'aurelia-dialog/dist/commonjs/ux-dialog.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/commonjs/ux-dialog'>;
}
declare module 'aurelia-dialog/dist/es2015/attach-focus.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/attach-focus'>;
}
declare module 'aurelia-dialog/dist/es2015/aurelia-dialog.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/aurelia-dialog'>;
}
declare module 'aurelia-dialog/dist/es2015/dialog-cancel-error.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/dialog-cancel-error'>;
}
declare module 'aurelia-dialog/dist/es2015/dialog-configuration.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/dialog-configuration'>;
}
declare module 'aurelia-dialog/dist/es2015/dialog-controller.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/dialog-controller'>;
}
declare module 'aurelia-dialog/dist/es2015/dialog-renderer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/dialog-renderer'>;
}
declare module 'aurelia-dialog/dist/es2015/dialog-result.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/dialog-result'>;
}
declare module 'aurelia-dialog/dist/es2015/dialog-service.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/dialog-service'>;
}
declare module 'aurelia-dialog/dist/es2015/dialog-settings.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/dialog-settings'>;
}
declare module 'aurelia-dialog/dist/es2015/interfaces.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/interfaces'>;
}
declare module 'aurelia-dialog/dist/es2015/lifecycle.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/lifecycle'>;
}
declare module 'aurelia-dialog/dist/es2015/renderer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/renderer'>;
}
declare module 'aurelia-dialog/dist/es2015/ux-dialog-body.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/ux-dialog-body'>;
}
declare module 'aurelia-dialog/dist/es2015/ux-dialog-footer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/ux-dialog-footer'>;
}
declare module 'aurelia-dialog/dist/es2015/ux-dialog-header.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/ux-dialog-header'>;
}
declare module 'aurelia-dialog/dist/es2015/ux-dialog.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/es2015/ux-dialog'>;
}
declare module 'aurelia-dialog/dist/native-modules/attach-focus.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/attach-focus'>;
}
declare module 'aurelia-dialog/dist/native-modules/aurelia-dialog.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/aurelia-dialog'>;
}
declare module 'aurelia-dialog/dist/native-modules/dialog-cancel-error.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/dialog-cancel-error'>;
}
declare module 'aurelia-dialog/dist/native-modules/dialog-configuration.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/dialog-configuration'>;
}
declare module 'aurelia-dialog/dist/native-modules/dialog-controller.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/dialog-controller'>;
}
declare module 'aurelia-dialog/dist/native-modules/dialog-renderer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/dialog-renderer'>;
}
declare module 'aurelia-dialog/dist/native-modules/dialog-result.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/dialog-result'>;
}
declare module 'aurelia-dialog/dist/native-modules/dialog-service.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/dialog-service'>;
}
declare module 'aurelia-dialog/dist/native-modules/dialog-settings.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/dialog-settings'>;
}
declare module 'aurelia-dialog/dist/native-modules/interfaces.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/interfaces'>;
}
declare module 'aurelia-dialog/dist/native-modules/lifecycle.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/lifecycle'>;
}
declare module 'aurelia-dialog/dist/native-modules/renderer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/renderer'>;
}
declare module 'aurelia-dialog/dist/native-modules/ux-dialog-body.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/ux-dialog-body'>;
}
declare module 'aurelia-dialog/dist/native-modules/ux-dialog-footer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/ux-dialog-footer'>;
}
declare module 'aurelia-dialog/dist/native-modules/ux-dialog-header.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/ux-dialog-header'>;
}
declare module 'aurelia-dialog/dist/native-modules/ux-dialog.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/native-modules/ux-dialog'>;
}
declare module 'aurelia-dialog/dist/system/attach-focus.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/attach-focus'>;
}
declare module 'aurelia-dialog/dist/system/aurelia-dialog.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/aurelia-dialog'>;
}
declare module 'aurelia-dialog/dist/system/dialog-cancel-error.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/dialog-cancel-error'>;
}
declare module 'aurelia-dialog/dist/system/dialog-configuration.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/dialog-configuration'>;
}
declare module 'aurelia-dialog/dist/system/dialog-controller.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/dialog-controller'>;
}
declare module 'aurelia-dialog/dist/system/dialog-renderer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/dialog-renderer'>;
}
declare module 'aurelia-dialog/dist/system/dialog-result.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/dialog-result'>;
}
declare module 'aurelia-dialog/dist/system/dialog-service.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/dialog-service'>;
}
declare module 'aurelia-dialog/dist/system/dialog-settings.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/dialog-settings'>;
}
declare module 'aurelia-dialog/dist/system/interfaces.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/interfaces'>;
}
declare module 'aurelia-dialog/dist/system/lifecycle.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/lifecycle'>;
}
declare module 'aurelia-dialog/dist/system/renderer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/renderer'>;
}
declare module 'aurelia-dialog/dist/system/ux-dialog-body.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/ux-dialog-body'>;
}
declare module 'aurelia-dialog/dist/system/ux-dialog-footer.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/ux-dialog-footer'>;
}
declare module 'aurelia-dialog/dist/system/ux-dialog-header.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/ux-dialog-header'>;
}
declare module 'aurelia-dialog/dist/system/ux-dialog.js' {
  declare module.exports: $Exports<'aurelia-dialog/dist/system/ux-dialog'>;
}
declare module 'aurelia-dialog/doc/example/common-dialogs.js' {
  declare module.exports: $Exports<'aurelia-dialog/doc/example/common-dialogs'>;
}
declare module 'aurelia-dialog/doc/example/prompt.js' {
  declare module.exports: $Exports<'aurelia-dialog/doc/example/prompt'>;
}
declare module 'aurelia-dialog/doc/shape-defs.js' {
  declare module.exports: $Exports<'aurelia-dialog/doc/shape-defs'>;
}
declare module 'aurelia-dialog/doc/shape-doc.js' {
  declare module.exports: $Exports<'aurelia-dialog/doc/shape-doc'>;
}
declare module 'aurelia-dialog/karma.conf.js' {
  declare module.exports: $Exports<'aurelia-dialog/karma.conf'>;
}
