// flow-typed signature: 89dba51f649ff9190a2d46b7f555f450
// flow-typed version: <<STUB>>/aurelia-router_v^1.3.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurelia-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurelia-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurelia-router/build/args' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/babel-options' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/paths' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/reports/coverage/html/prettify' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/reports/coverage/html/sorter' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/tasks/build' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/tasks/clean' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/tasks/dev' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/tasks/doc' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/tasks/lint' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/tasks/prepare-release' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/tasks/test' {
  declare module.exports: any;
}

declare module 'aurelia-router/build/typescript-options' {
  declare module.exports: any;
}

declare module 'aurelia-router/config' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/amd/aurelia-router' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/amd/index' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/aurelia-router' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/commonjs/aurelia-router' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/es2015/aurelia-router' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/es2015/index' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/native-modules/aurelia-router' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/native-modules/index' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/system/aurelia-router' {
  declare module.exports: any;
}

declare module 'aurelia-router/dist/system/index' {
  declare module.exports: any;
}

declare module 'aurelia-router/gulpfile' {
  declare module.exports: any;
}

declare module 'aurelia-router/karma.conf' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/activation' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/app-router' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/interfaces' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/nav-model' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/navigation-commands' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/navigation-instruction' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/navigation-plan' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/pipeline-provider' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/pipeline' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/route-loading' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/router-configuration' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/router' {
  declare module.exports: any;
}

declare module 'aurelia-router/src/util' {
  declare module.exports: any;
}

declare module 'aurelia-router/test/activation.spec' {
  declare module.exports: any;
}

declare module 'aurelia-router/test/app-router.spec' {
  declare module.exports: any;
}

declare module 'aurelia-router/test/navigation-commands.spec' {
  declare module.exports: any;
}

declare module 'aurelia-router/test/navigation-instruction.spec' {
  declare module.exports: any;
}

declare module 'aurelia-router/test/navigation-plan.spec' {
  declare module.exports: any;
}

declare module 'aurelia-router/test/router.spec' {
  declare module.exports: any;
}

declare module 'aurelia-router/test/test-util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurelia-router/build/args.js' {
  declare module.exports: $Exports<'aurelia-router/build/args'>;
}
declare module 'aurelia-router/build/babel-options.js' {
  declare module.exports: $Exports<'aurelia-router/build/babel-options'>;
}
declare module 'aurelia-router/build/paths.js' {
  declare module.exports: $Exports<'aurelia-router/build/paths'>;
}
declare module 'aurelia-router/build/reports/coverage/html/prettify.js' {
  declare module.exports: $Exports<'aurelia-router/build/reports/coverage/html/prettify'>;
}
declare module 'aurelia-router/build/reports/coverage/html/sorter.js' {
  declare module.exports: $Exports<'aurelia-router/build/reports/coverage/html/sorter'>;
}
declare module 'aurelia-router/build/tasks/build.js' {
  declare module.exports: $Exports<'aurelia-router/build/tasks/build'>;
}
declare module 'aurelia-router/build/tasks/clean.js' {
  declare module.exports: $Exports<'aurelia-router/build/tasks/clean'>;
}
declare module 'aurelia-router/build/tasks/dev.js' {
  declare module.exports: $Exports<'aurelia-router/build/tasks/dev'>;
}
declare module 'aurelia-router/build/tasks/doc.js' {
  declare module.exports: $Exports<'aurelia-router/build/tasks/doc'>;
}
declare module 'aurelia-router/build/tasks/lint.js' {
  declare module.exports: $Exports<'aurelia-router/build/tasks/lint'>;
}
declare module 'aurelia-router/build/tasks/prepare-release.js' {
  declare module.exports: $Exports<'aurelia-router/build/tasks/prepare-release'>;
}
declare module 'aurelia-router/build/tasks/test.js' {
  declare module.exports: $Exports<'aurelia-router/build/tasks/test'>;
}
declare module 'aurelia-router/build/typescript-options.js' {
  declare module.exports: $Exports<'aurelia-router/build/typescript-options'>;
}
declare module 'aurelia-router/config.js' {
  declare module.exports: $Exports<'aurelia-router/config'>;
}
declare module 'aurelia-router/dist/amd/aurelia-router.js' {
  declare module.exports: $Exports<'aurelia-router/dist/amd/aurelia-router'>;
}
declare module 'aurelia-router/dist/amd/index.js' {
  declare module.exports: $Exports<'aurelia-router/dist/amd/index'>;
}
declare module 'aurelia-router/dist/aurelia-router.js' {
  declare module.exports: $Exports<'aurelia-router/dist/aurelia-router'>;
}
declare module 'aurelia-router/dist/commonjs/aurelia-router.js' {
  declare module.exports: $Exports<'aurelia-router/dist/commonjs/aurelia-router'>;
}
declare module 'aurelia-router/dist/commonjs/index.js' {
  declare module.exports: $Exports<'aurelia-router/dist/commonjs/index'>;
}
declare module 'aurelia-router/dist/es2015/aurelia-router.js' {
  declare module.exports: $Exports<'aurelia-router/dist/es2015/aurelia-router'>;
}
declare module 'aurelia-router/dist/es2015/index.js' {
  declare module.exports: $Exports<'aurelia-router/dist/es2015/index'>;
}
declare module 'aurelia-router/dist/native-modules/aurelia-router.js' {
  declare module.exports: $Exports<'aurelia-router/dist/native-modules/aurelia-router'>;
}
declare module 'aurelia-router/dist/native-modules/index.js' {
  declare module.exports: $Exports<'aurelia-router/dist/native-modules/index'>;
}
declare module 'aurelia-router/dist/system/aurelia-router.js' {
  declare module.exports: $Exports<'aurelia-router/dist/system/aurelia-router'>;
}
declare module 'aurelia-router/dist/system/index.js' {
  declare module.exports: $Exports<'aurelia-router/dist/system/index'>;
}
declare module 'aurelia-router/gulpfile.js' {
  declare module.exports: $Exports<'aurelia-router/gulpfile'>;
}
declare module 'aurelia-router/karma.conf.js' {
  declare module.exports: $Exports<'aurelia-router/karma.conf'>;
}
declare module 'aurelia-router/src/activation.js' {
  declare module.exports: $Exports<'aurelia-router/src/activation'>;
}
declare module 'aurelia-router/src/app-router.js' {
  declare module.exports: $Exports<'aurelia-router/src/app-router'>;
}
declare module 'aurelia-router/src/interfaces.js' {
  declare module.exports: $Exports<'aurelia-router/src/interfaces'>;
}
declare module 'aurelia-router/src/nav-model.js' {
  declare module.exports: $Exports<'aurelia-router/src/nav-model'>;
}
declare module 'aurelia-router/src/navigation-commands.js' {
  declare module.exports: $Exports<'aurelia-router/src/navigation-commands'>;
}
declare module 'aurelia-router/src/navigation-instruction.js' {
  declare module.exports: $Exports<'aurelia-router/src/navigation-instruction'>;
}
declare module 'aurelia-router/src/navigation-plan.js' {
  declare module.exports: $Exports<'aurelia-router/src/navigation-plan'>;
}
declare module 'aurelia-router/src/pipeline-provider.js' {
  declare module.exports: $Exports<'aurelia-router/src/pipeline-provider'>;
}
declare module 'aurelia-router/src/pipeline.js' {
  declare module.exports: $Exports<'aurelia-router/src/pipeline'>;
}
declare module 'aurelia-router/src/route-loading.js' {
  declare module.exports: $Exports<'aurelia-router/src/route-loading'>;
}
declare module 'aurelia-router/src/router-configuration.js' {
  declare module.exports: $Exports<'aurelia-router/src/router-configuration'>;
}
declare module 'aurelia-router/src/router.js' {
  declare module.exports: $Exports<'aurelia-router/src/router'>;
}
declare module 'aurelia-router/src/util.js' {
  declare module.exports: $Exports<'aurelia-router/src/util'>;
}
declare module 'aurelia-router/test/activation.spec.js' {
  declare module.exports: $Exports<'aurelia-router/test/activation.spec'>;
}
declare module 'aurelia-router/test/app-router.spec.js' {
  declare module.exports: $Exports<'aurelia-router/test/app-router.spec'>;
}
declare module 'aurelia-router/test/navigation-commands.spec.js' {
  declare module.exports: $Exports<'aurelia-router/test/navigation-commands.spec'>;
}
declare module 'aurelia-router/test/navigation-instruction.spec.js' {
  declare module.exports: $Exports<'aurelia-router/test/navigation-instruction.spec'>;
}
declare module 'aurelia-router/test/navigation-plan.spec.js' {
  declare module.exports: $Exports<'aurelia-router/test/navigation-plan.spec'>;
}
declare module 'aurelia-router/test/router.spec.js' {
  declare module.exports: $Exports<'aurelia-router/test/router.spec'>;
}
declare module 'aurelia-router/test/test-util.js' {
  declare module.exports: $Exports<'aurelia-router/test/test-util'>;
}
