// flow-typed signature: 30e062e45c65d0a619e203e50ce118f4
// flow-typed version: <<STUB>>/aurelia-testing_v^1.0.0-beta.2.0.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurelia-testing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurelia-testing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurelia-testing/build/args' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/babel-options' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/paths' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/tasks/build' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/tasks/ci' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/tasks/clean' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/tasks/dev' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/tasks/doc' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/tasks/lint' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/tasks/prepare-release' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/tasks/test' {
  declare module.exports: any;
}

declare module 'aurelia-testing/build/typescript-options' {
  declare module.exports: any;
}

declare module 'aurelia-testing/config' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/amd/aurelia-testing' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/amd/compile-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/amd/component-tester' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/amd/index' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/amd/view-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/amd/wait' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/aurelia-testing' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/commonjs/aurelia-testing' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/commonjs/compile-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/commonjs/component-tester' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/commonjs/view-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/commonjs/wait' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/es2015/aurelia-testing' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/es2015/compile-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/es2015/component-tester' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/es2015/index' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/es2015/view-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/es2015/wait' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/native-modules/aurelia-testing' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/native-modules/compile-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/native-modules/component-tester' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/native-modules/index' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/native-modules/view-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/native-modules/wait' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/system/aurelia-testing' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/system/compile-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/system/component-tester' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/system/index' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/system/view-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/system/wait' {
  declare module.exports: any;
}

declare module 'aurelia-testing/dist/temp/aurelia-testing' {
  declare module.exports: any;
}

declare module 'aurelia-testing/gulpfile' {
  declare module.exports: any;
}

declare module 'aurelia-testing/karma.conf' {
  declare module.exports: any;
}

declare module 'aurelia-testing/src/aurelia-testing' {
  declare module.exports: any;
}

declare module 'aurelia-testing/src/compile-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/src/component-tester' {
  declare module.exports: any;
}

declare module 'aurelia-testing/src/view-spy' {
  declare module.exports: any;
}

declare module 'aurelia-testing/src/wait' {
  declare module.exports: any;
}

declare module 'aurelia-testing/test/component-tester.spec' {
  declare module.exports: any;
}

declare module 'aurelia-testing/test/doc-samples.spec' {
  declare module.exports: any;
}

declare module 'aurelia-testing/test/resources/my-attribute' {
  declare module.exports: any;
}

declare module 'aurelia-testing/test/resources/my-component' {
  declare module.exports: any;
}

declare module 'aurelia-testing/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurelia-testing/build/args.js' {
  declare module.exports: $Exports<'aurelia-testing/build/args'>;
}
declare module 'aurelia-testing/build/babel-options.js' {
  declare module.exports: $Exports<'aurelia-testing/build/babel-options'>;
}
declare module 'aurelia-testing/build/paths.js' {
  declare module.exports: $Exports<'aurelia-testing/build/paths'>;
}
declare module 'aurelia-testing/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify.js' {
  declare module.exports: $Exports<'aurelia-testing/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify'>;
}
declare module 'aurelia-testing/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter.js' {
  declare module.exports: $Exports<'aurelia-testing/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter'>;
}
declare module 'aurelia-testing/build/tasks/build.js' {
  declare module.exports: $Exports<'aurelia-testing/build/tasks/build'>;
}
declare module 'aurelia-testing/build/tasks/ci.js' {
  declare module.exports: $Exports<'aurelia-testing/build/tasks/ci'>;
}
declare module 'aurelia-testing/build/tasks/clean.js' {
  declare module.exports: $Exports<'aurelia-testing/build/tasks/clean'>;
}
declare module 'aurelia-testing/build/tasks/dev.js' {
  declare module.exports: $Exports<'aurelia-testing/build/tasks/dev'>;
}
declare module 'aurelia-testing/build/tasks/doc.js' {
  declare module.exports: $Exports<'aurelia-testing/build/tasks/doc'>;
}
declare module 'aurelia-testing/build/tasks/lint.js' {
  declare module.exports: $Exports<'aurelia-testing/build/tasks/lint'>;
}
declare module 'aurelia-testing/build/tasks/prepare-release.js' {
  declare module.exports: $Exports<'aurelia-testing/build/tasks/prepare-release'>;
}
declare module 'aurelia-testing/build/tasks/test.js' {
  declare module.exports: $Exports<'aurelia-testing/build/tasks/test'>;
}
declare module 'aurelia-testing/build/typescript-options.js' {
  declare module.exports: $Exports<'aurelia-testing/build/typescript-options'>;
}
declare module 'aurelia-testing/config.js' {
  declare module.exports: $Exports<'aurelia-testing/config'>;
}
declare module 'aurelia-testing/dist/amd/aurelia-testing.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/amd/aurelia-testing'>;
}
declare module 'aurelia-testing/dist/amd/compile-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/amd/compile-spy'>;
}
declare module 'aurelia-testing/dist/amd/component-tester.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/amd/component-tester'>;
}
declare module 'aurelia-testing/dist/amd/index.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/amd/index'>;
}
declare module 'aurelia-testing/dist/amd/view-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/amd/view-spy'>;
}
declare module 'aurelia-testing/dist/amd/wait.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/amd/wait'>;
}
declare module 'aurelia-testing/dist/aurelia-testing.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/aurelia-testing'>;
}
declare module 'aurelia-testing/dist/commonjs/aurelia-testing.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/commonjs/aurelia-testing'>;
}
declare module 'aurelia-testing/dist/commonjs/compile-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/commonjs/compile-spy'>;
}
declare module 'aurelia-testing/dist/commonjs/component-tester.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/commonjs/component-tester'>;
}
declare module 'aurelia-testing/dist/commonjs/index.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/commonjs/index'>;
}
declare module 'aurelia-testing/dist/commonjs/view-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/commonjs/view-spy'>;
}
declare module 'aurelia-testing/dist/commonjs/wait.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/commonjs/wait'>;
}
declare module 'aurelia-testing/dist/es2015/aurelia-testing.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/es2015/aurelia-testing'>;
}
declare module 'aurelia-testing/dist/es2015/compile-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/es2015/compile-spy'>;
}
declare module 'aurelia-testing/dist/es2015/component-tester.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/es2015/component-tester'>;
}
declare module 'aurelia-testing/dist/es2015/index.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/es2015/index'>;
}
declare module 'aurelia-testing/dist/es2015/view-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/es2015/view-spy'>;
}
declare module 'aurelia-testing/dist/es2015/wait.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/es2015/wait'>;
}
declare module 'aurelia-testing/dist/native-modules/aurelia-testing.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/native-modules/aurelia-testing'>;
}
declare module 'aurelia-testing/dist/native-modules/compile-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/native-modules/compile-spy'>;
}
declare module 'aurelia-testing/dist/native-modules/component-tester.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/native-modules/component-tester'>;
}
declare module 'aurelia-testing/dist/native-modules/index.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/native-modules/index'>;
}
declare module 'aurelia-testing/dist/native-modules/view-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/native-modules/view-spy'>;
}
declare module 'aurelia-testing/dist/native-modules/wait.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/native-modules/wait'>;
}
declare module 'aurelia-testing/dist/system/aurelia-testing.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/system/aurelia-testing'>;
}
declare module 'aurelia-testing/dist/system/compile-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/system/compile-spy'>;
}
declare module 'aurelia-testing/dist/system/component-tester.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/system/component-tester'>;
}
declare module 'aurelia-testing/dist/system/index.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/system/index'>;
}
declare module 'aurelia-testing/dist/system/view-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/system/view-spy'>;
}
declare module 'aurelia-testing/dist/system/wait.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/system/wait'>;
}
declare module 'aurelia-testing/dist/temp/aurelia-testing.js' {
  declare module.exports: $Exports<'aurelia-testing/dist/temp/aurelia-testing'>;
}
declare module 'aurelia-testing/gulpfile.js' {
  declare module.exports: $Exports<'aurelia-testing/gulpfile'>;
}
declare module 'aurelia-testing/karma.conf.js' {
  declare module.exports: $Exports<'aurelia-testing/karma.conf'>;
}
declare module 'aurelia-testing/src/aurelia-testing.js' {
  declare module.exports: $Exports<'aurelia-testing/src/aurelia-testing'>;
}
declare module 'aurelia-testing/src/compile-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/src/compile-spy'>;
}
declare module 'aurelia-testing/src/component-tester.js' {
  declare module.exports: $Exports<'aurelia-testing/src/component-tester'>;
}
declare module 'aurelia-testing/src/view-spy.js' {
  declare module.exports: $Exports<'aurelia-testing/src/view-spy'>;
}
declare module 'aurelia-testing/src/wait.js' {
  declare module.exports: $Exports<'aurelia-testing/src/wait'>;
}
declare module 'aurelia-testing/test/component-tester.spec.js' {
  declare module.exports: $Exports<'aurelia-testing/test/component-tester.spec'>;
}
declare module 'aurelia-testing/test/doc-samples.spec.js' {
  declare module.exports: $Exports<'aurelia-testing/test/doc-samples.spec'>;
}
declare module 'aurelia-testing/test/resources/my-attribute.js' {
  declare module.exports: $Exports<'aurelia-testing/test/resources/my-attribute'>;
}
declare module 'aurelia-testing/test/resources/my-component.js' {
  declare module.exports: $Exports<'aurelia-testing/test/resources/my-component'>;
}
declare module 'aurelia-testing/test/setup.js' {
  declare module.exports: $Exports<'aurelia-testing/test/setup'>;
}
