// flow-typed signature: c40703db62a3b306bbbaae186ac99dc6
// flow-typed version: <<STUB>>/aurelia-framework_v1.1.4/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurelia-framework'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurelia-framework' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurelia-framework/build/args' {
  declare module.exports: any;
}

declare module 'aurelia-framework/build/babel-options' {
  declare module.exports: any;
}

declare module 'aurelia-framework/build/paths' {
  declare module.exports: any;
}

declare module 'aurelia-framework/build/tasks/build' {
  declare module.exports: any;
}

declare module 'aurelia-framework/build/tasks/clean' {
  declare module.exports: any;
}

declare module 'aurelia-framework/build/tasks/dev' {
  declare module.exports: any;
}

declare module 'aurelia-framework/build/tasks/doc' {
  declare module.exports: any;
}

declare module 'aurelia-framework/build/tasks/lint' {
  declare module.exports: any;
}

declare module 'aurelia-framework/build/tasks/prepare-release' {
  declare module.exports: any;
}

declare module 'aurelia-framework/build/tasks/test' {
  declare module.exports: any;
}

declare module 'aurelia-framework/build/typescript-options' {
  declare module.exports: any;
}

declare module 'aurelia-framework/config' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/amd/aurelia-framework' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/amd/index' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/aurelia-framework' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/commonjs/aurelia-framework' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/es2015/aurelia-framework' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/es2015/index' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/native-modules/aurelia-framework' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/native-modules/index' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/system/aurelia-framework' {
  declare module.exports: any;
}

declare module 'aurelia-framework/dist/system/index' {
  declare module.exports: any;
}

declare module 'aurelia-framework/gulpfile' {
  declare module.exports: any;
}

declare module 'aurelia-framework/karma.conf' {
  declare module.exports: any;
}

declare module 'aurelia-framework/src/aurelia' {
  declare module.exports: any;
}

declare module 'aurelia-framework/src/framework-configuration' {
  declare module.exports: any;
}

declare module 'aurelia-framework/src/index' {
  declare module.exports: any;
}

declare module 'aurelia-framework/test/aurelia.spec' {
  declare module.exports: any;
}

declare module 'aurelia-framework/test/framework-configuration' {
  declare module.exports: any;
}

declare module 'aurelia-framework/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurelia-framework/build/args.js' {
  declare module.exports: $Exports<'aurelia-framework/build/args'>;
}
declare module 'aurelia-framework/build/babel-options.js' {
  declare module.exports: $Exports<'aurelia-framework/build/babel-options'>;
}
declare module 'aurelia-framework/build/paths.js' {
  declare module.exports: $Exports<'aurelia-framework/build/paths'>;
}
declare module 'aurelia-framework/build/tasks/build.js' {
  declare module.exports: $Exports<'aurelia-framework/build/tasks/build'>;
}
declare module 'aurelia-framework/build/tasks/clean.js' {
  declare module.exports: $Exports<'aurelia-framework/build/tasks/clean'>;
}
declare module 'aurelia-framework/build/tasks/dev.js' {
  declare module.exports: $Exports<'aurelia-framework/build/tasks/dev'>;
}
declare module 'aurelia-framework/build/tasks/doc.js' {
  declare module.exports: $Exports<'aurelia-framework/build/tasks/doc'>;
}
declare module 'aurelia-framework/build/tasks/lint.js' {
  declare module.exports: $Exports<'aurelia-framework/build/tasks/lint'>;
}
declare module 'aurelia-framework/build/tasks/prepare-release.js' {
  declare module.exports: $Exports<'aurelia-framework/build/tasks/prepare-release'>;
}
declare module 'aurelia-framework/build/tasks/test.js' {
  declare module.exports: $Exports<'aurelia-framework/build/tasks/test'>;
}
declare module 'aurelia-framework/build/typescript-options.js' {
  declare module.exports: $Exports<'aurelia-framework/build/typescript-options'>;
}
declare module 'aurelia-framework/config.js' {
  declare module.exports: $Exports<'aurelia-framework/config'>;
}
declare module 'aurelia-framework/dist/amd/aurelia-framework.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/amd/aurelia-framework'>;
}
declare module 'aurelia-framework/dist/amd/index.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/amd/index'>;
}
declare module 'aurelia-framework/dist/aurelia-framework.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/aurelia-framework'>;
}
declare module 'aurelia-framework/dist/commonjs/aurelia-framework.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/commonjs/aurelia-framework'>;
}
declare module 'aurelia-framework/dist/commonjs/index.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/commonjs/index'>;
}
declare module 'aurelia-framework/dist/es2015/aurelia-framework.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/es2015/aurelia-framework'>;
}
declare module 'aurelia-framework/dist/es2015/index.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/es2015/index'>;
}
declare module 'aurelia-framework/dist/native-modules/aurelia-framework.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/native-modules/aurelia-framework'>;
}
declare module 'aurelia-framework/dist/native-modules/index.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/native-modules/index'>;
}
declare module 'aurelia-framework/dist/system/aurelia-framework.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/system/aurelia-framework'>;
}
declare module 'aurelia-framework/dist/system/index.js' {
  declare module.exports: $Exports<'aurelia-framework/dist/system/index'>;
}
declare module 'aurelia-framework/gulpfile.js' {
  declare module.exports: $Exports<'aurelia-framework/gulpfile'>;
}
declare module 'aurelia-framework/karma.conf.js' {
  declare module.exports: $Exports<'aurelia-framework/karma.conf'>;
}
declare module 'aurelia-framework/src/aurelia.js' {
  declare module.exports: $Exports<'aurelia-framework/src/aurelia'>;
}
declare module 'aurelia-framework/src/framework-configuration.js' {
  declare module.exports: $Exports<'aurelia-framework/src/framework-configuration'>;
}
declare module 'aurelia-framework/src/index.js' {
  declare module.exports: $Exports<'aurelia-framework/src/index'>;
}
declare module 'aurelia-framework/test/aurelia.spec.js' {
  declare module.exports: $Exports<'aurelia-framework/test/aurelia.spec'>;
}
declare module 'aurelia-framework/test/framework-configuration.js' {
  declare module.exports: $Exports<'aurelia-framework/test/framework-configuration'>;
}
declare module 'aurelia-framework/test/setup.js' {
  declare module.exports: $Exports<'aurelia-framework/test/setup'>;
}
