// flow-typed signature: 328b0b07da0b07703b42bc812cc01357
// flow-typed version: <<STUB>>/aurelia-bootstrapper_v^2.1.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurelia-bootstrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurelia-bootstrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurelia-bootstrapper/build/args' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/build/babel-options' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/build/paths' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/build/tasks/build' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/build/tasks/clean' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/build/tasks/dev' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/build/tasks/doc' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/build/tasks/lint' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/build/tasks/prepare-release' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/build/tasks/test' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/build/typescript-options' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/config' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/amd/aurelia-bootstrapper' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/amd/index' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/aurelia-bootstrapper' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/commonjs/aurelia-bootstrapper' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/es2015/aurelia-bootstrapper' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/es2015/index' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/native-modules/index' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/system/aurelia-bootstrapper' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/dist/system/index' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/gulpfile' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/karma.conf' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/src/index' {
  declare module.exports: any;
}

declare module 'aurelia-bootstrapper/test/bootstrapper.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurelia-bootstrapper/build/args.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/args'>;
}
declare module 'aurelia-bootstrapper/build/babel-options.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/babel-options'>;
}
declare module 'aurelia-bootstrapper/build/paths.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/paths'>;
}
declare module 'aurelia-bootstrapper/build/tasks/build.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/tasks/build'>;
}
declare module 'aurelia-bootstrapper/build/tasks/clean.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/tasks/clean'>;
}
declare module 'aurelia-bootstrapper/build/tasks/dev.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/tasks/dev'>;
}
declare module 'aurelia-bootstrapper/build/tasks/doc.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/tasks/doc'>;
}
declare module 'aurelia-bootstrapper/build/tasks/lint.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/tasks/lint'>;
}
declare module 'aurelia-bootstrapper/build/tasks/prepare-release.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/tasks/prepare-release'>;
}
declare module 'aurelia-bootstrapper/build/tasks/test.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/tasks/test'>;
}
declare module 'aurelia-bootstrapper/build/typescript-options.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/build/typescript-options'>;
}
declare module 'aurelia-bootstrapper/config.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/config'>;
}
declare module 'aurelia-bootstrapper/dist/amd/aurelia-bootstrapper.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/amd/aurelia-bootstrapper'>;
}
declare module 'aurelia-bootstrapper/dist/amd/index.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/amd/index'>;
}
declare module 'aurelia-bootstrapper/dist/aurelia-bootstrapper.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/aurelia-bootstrapper'>;
}
declare module 'aurelia-bootstrapper/dist/commonjs/aurelia-bootstrapper.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/commonjs/aurelia-bootstrapper'>;
}
declare module 'aurelia-bootstrapper/dist/commonjs/index.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/commonjs/index'>;
}
declare module 'aurelia-bootstrapper/dist/es2015/aurelia-bootstrapper.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/es2015/aurelia-bootstrapper'>;
}
declare module 'aurelia-bootstrapper/dist/es2015/index.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/es2015/index'>;
}
declare module 'aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper'>;
}
declare module 'aurelia-bootstrapper/dist/native-modules/index.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/native-modules/index'>;
}
declare module 'aurelia-bootstrapper/dist/system/aurelia-bootstrapper.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/system/aurelia-bootstrapper'>;
}
declare module 'aurelia-bootstrapper/dist/system/index.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/dist/system/index'>;
}
declare module 'aurelia-bootstrapper/gulpfile.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/gulpfile'>;
}
declare module 'aurelia-bootstrapper/karma.conf.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/karma.conf'>;
}
declare module 'aurelia-bootstrapper/src/index.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/src/index'>;
}
declare module 'aurelia-bootstrapper/test/bootstrapper.spec.js' {
  declare module.exports: $Exports<'aurelia-bootstrapper/test/bootstrapper.spec'>;
}
