// flow-typed signature: 0f9bb2b33bf0e4ad06e753d0c0f8250d
// flow-typed version: <<STUB>>/aurelia-fetch-client_v^1.1.3/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurelia-fetch-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurelia-fetch-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurelia-fetch-client/build/args' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/babel-options' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/paths' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/reports/coverage/html/prettify' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/reports/coverage/html/sorter' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/tasks/build' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/tasks/ci' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/tasks/clean' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/tasks/default' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/tasks/dev' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/tasks/doc' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/tasks/lint' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/tasks/prepare-release' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/tasks/test' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/build/typescript-options' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/config' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/amd/aurelia-fetch-client' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/amd/index' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/aurelia-fetch-client' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/commonjs/aurelia-fetch-client' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/es2015/aurelia-fetch-client' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/es2015/index' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/native-modules/aurelia-fetch-client' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/native-modules/index' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/system/aurelia-fetch-client' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/dist/system/index' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/gulpfile' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/karma.conf' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/src/http-client-configuration' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/src/http-client' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/src/interfaces' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/src/util' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/test/http-client.spec' {
  declare module.exports: any;
}

declare module 'aurelia-fetch-client/test/util.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurelia-fetch-client/build/args.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/args'>;
}
declare module 'aurelia-fetch-client/build/babel-options.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/babel-options'>;
}
declare module 'aurelia-fetch-client/build/paths.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/paths'>;
}
declare module 'aurelia-fetch-client/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify'>;
}
declare module 'aurelia-fetch-client/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter'>;
}
declare module 'aurelia-fetch-client/build/reports/coverage/html/prettify.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/reports/coverage/html/prettify'>;
}
declare module 'aurelia-fetch-client/build/reports/coverage/html/sorter.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/reports/coverage/html/sorter'>;
}
declare module 'aurelia-fetch-client/build/tasks/build.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/tasks/build'>;
}
declare module 'aurelia-fetch-client/build/tasks/ci.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/tasks/ci'>;
}
declare module 'aurelia-fetch-client/build/tasks/clean.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/tasks/clean'>;
}
declare module 'aurelia-fetch-client/build/tasks/default.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/tasks/default'>;
}
declare module 'aurelia-fetch-client/build/tasks/dev.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/tasks/dev'>;
}
declare module 'aurelia-fetch-client/build/tasks/doc.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/tasks/doc'>;
}
declare module 'aurelia-fetch-client/build/tasks/lint.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/tasks/lint'>;
}
declare module 'aurelia-fetch-client/build/tasks/prepare-release.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/tasks/prepare-release'>;
}
declare module 'aurelia-fetch-client/build/tasks/test.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/tasks/test'>;
}
declare module 'aurelia-fetch-client/build/typescript-options.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/build/typescript-options'>;
}
declare module 'aurelia-fetch-client/config.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/config'>;
}
declare module 'aurelia-fetch-client/dist/amd/aurelia-fetch-client.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/amd/aurelia-fetch-client'>;
}
declare module 'aurelia-fetch-client/dist/amd/index.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/amd/index'>;
}
declare module 'aurelia-fetch-client/dist/aurelia-fetch-client.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/aurelia-fetch-client'>;
}
declare module 'aurelia-fetch-client/dist/commonjs/aurelia-fetch-client.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/commonjs/aurelia-fetch-client'>;
}
declare module 'aurelia-fetch-client/dist/commonjs/index.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/commonjs/index'>;
}
declare module 'aurelia-fetch-client/dist/es2015/aurelia-fetch-client.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/es2015/aurelia-fetch-client'>;
}
declare module 'aurelia-fetch-client/dist/es2015/index.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/es2015/index'>;
}
declare module 'aurelia-fetch-client/dist/native-modules/aurelia-fetch-client.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/native-modules/aurelia-fetch-client'>;
}
declare module 'aurelia-fetch-client/dist/native-modules/index.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/native-modules/index'>;
}
declare module 'aurelia-fetch-client/dist/system/aurelia-fetch-client.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/system/aurelia-fetch-client'>;
}
declare module 'aurelia-fetch-client/dist/system/index.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/dist/system/index'>;
}
declare module 'aurelia-fetch-client/gulpfile.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/gulpfile'>;
}
declare module 'aurelia-fetch-client/karma.conf.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/karma.conf'>;
}
declare module 'aurelia-fetch-client/src/http-client-configuration.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/src/http-client-configuration'>;
}
declare module 'aurelia-fetch-client/src/http-client.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/src/http-client'>;
}
declare module 'aurelia-fetch-client/src/interfaces.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/src/interfaces'>;
}
declare module 'aurelia-fetch-client/src/util.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/src/util'>;
}
declare module 'aurelia-fetch-client/test/http-client.spec.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/test/http-client.spec'>;
}
declare module 'aurelia-fetch-client/test/util.spec.js' {
  declare module.exports: $Exports<'aurelia-fetch-client/test/util.spec'>;
}
