// flow-typed signature: ad880fe3bc1a9f12df53251a50661820
// flow-typed version: <<STUB>>/aurelia-cli_v^0.27.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurelia-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurelia-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurelia-cli/bin/aurelia-cli' {
  declare module.exports: any;
}

declare module 'aurelia-cli/build/args' {
  declare module.exports: any;
}

declare module 'aurelia-cli/build/paths' {
  declare module.exports: any;
}

declare module 'aurelia-cli/build/tasks/lint' {
  declare module.exports: any;
}

declare module 'aurelia-cli/build/tasks/prepare-release' {
  declare module.exports: any;
}

declare module 'aurelia-cli/gulpfile' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/config' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/lib/lang' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/lib/loader/Loader' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/lib/loader/require' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/lib/parse' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/lib/prim' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/lib/prom' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/lib/transform' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/node_modules/esprima/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/read/cjs' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/write/all' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/write/defines' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/write/packages' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/write/plugins' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/amodro-trace/write/stubs' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/bundle' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/bundled-source' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/bundler' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/concat-with-sourcemaps/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/convert-source-map/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/dependency-description' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/dependency-inclusion' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/loader-plugin' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/loader' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/map-stream/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/package-analyzer' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/source-inclusion' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/build/utils' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/cli-options' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/cli' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/colors/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/colors/styles' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/colors/supports-colors' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/colors/transform' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/generate/command' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/gulp' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/help/command' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/import/command' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/install/command' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/install/package-argument-parser' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/command' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/css-processors/less' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/css-processors/none' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/css-processors/postcss' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/css-processors/sass' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/css-processors/stylus' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/editors/atom' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/editors/none' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/editors/sublime' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/editors/visualstudio' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/editors/vscode' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/editors/webstorm' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/markup-processors/maximum' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/markup-processors/minimum' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/markup-processors/none' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/markup-processors/pug' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/platforms/aspnetcore' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/platforms/web' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/project-template' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/transpilers/babel' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/transpilers/typescript' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/unit-test-runners/karma' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/new/unit-test-runners/none' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/commands/uninstall/command' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/dependencies' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/file-system' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/import-engine' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/package-importer' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/package-installer' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/package' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/services/metadata-service' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/services/registry' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/services/resource-inclusion' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/services/tutorial' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/strategies/amodro' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/strategies/aurelia-registry' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/strategies/browser-section' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/strategies/custom-importer' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/strategies/jspm-section' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/strategies/metadata' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/importer/strategy-loader' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/logger' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/mkdirp' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/npm' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/package-managers/npm' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/package-managers/yarn' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/project-item' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/project' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resolve/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resolve/lib/async' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resolve/lib/caller' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resolve/lib/core' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resolve/lib/node-modules-paths' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resolve/lib/sync' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/content/karma.conf' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/environments/dev' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/environments/prod' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/environments/stage' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/generators/attribute' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/generators/binding-behavior' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/generators/component' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/generators/element' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/generators/generator' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/generators/task' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/generators/value-converter' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/scripts/configure-bluebird' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/scripts/require' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/scripts/text' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/src/app' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/src/main' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/src/resources/index' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/build' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/copy-files' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/process-css' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/process-less' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/process-markup-minify-max' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/process-markup-minify-min' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/process-markup' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/process-postcss' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/process-pug' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/process-sass' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/process-stylus' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/run' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/test' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/tasks/transpile' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/test/app.spec' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/test/aurelia-karma' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/resources/test/setup' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/string' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/ui' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/workflow/activities/branch-switch' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/workflow/activities/input-select' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/workflow/activities/input-text' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/workflow/activities/project-create' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/workflow/activities/project-install' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/workflow/activities/state-assign' {
  declare module.exports: any;
}

declare module 'aurelia-cli/lib/workflow/workflow-engine' {
  declare module.exports: any;
}

declare module 'aurelia-cli/spec/helpers/polyfills' {
  declare module.exports: any;
}

declare module 'aurelia-cli/spec/lib/cli.spec' {
  declare module.exports: any;
}

declare module 'aurelia-cli/spec/lib/file-system.spec' {
  declare module.exports: any;
}

declare module 'aurelia-cli/spec/lib/project-item.spec' {
  declare module.exports: any;
}

declare module 'aurelia-cli/spec/lib/project.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurelia-cli/bin/aurelia-cli.js' {
  declare module.exports: $Exports<'aurelia-cli/bin/aurelia-cli'>;
}
declare module 'aurelia-cli/build/args.js' {
  declare module.exports: $Exports<'aurelia-cli/build/args'>;
}
declare module 'aurelia-cli/build/paths.js' {
  declare module.exports: $Exports<'aurelia-cli/build/paths'>;
}
declare module 'aurelia-cli/build/tasks/lint.js' {
  declare module.exports: $Exports<'aurelia-cli/build/tasks/lint'>;
}
declare module 'aurelia-cli/build/tasks/prepare-release.js' {
  declare module.exports: $Exports<'aurelia-cli/build/tasks/prepare-release'>;
}
declare module 'aurelia-cli/gulpfile.js' {
  declare module.exports: $Exports<'aurelia-cli/gulpfile'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/config.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/config'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/index'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/lib/lang.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/lib/lang'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/lib/loader/Loader'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/lib/loader/require.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/lib/loader/require'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/lib/parse.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/lib/parse'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/lib/prim.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/lib/prim'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/lib/prom.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/lib/prom'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/lib/transform.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/lib/transform'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/node_modules/esprima/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/node_modules/esprima/index'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/read/cjs.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/read/cjs'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/write/all.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/write/all'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/write/defines.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/write/defines'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/write/packages.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/write/packages'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/write/plugins.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/write/plugins'>;
}
declare module 'aurelia-cli/lib/build/amodro-trace/write/stubs.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/amodro-trace/write/stubs'>;
}
declare module 'aurelia-cli/lib/build/bundle.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/bundle'>;
}
declare module 'aurelia-cli/lib/build/bundled-source.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/bundled-source'>;
}
declare module 'aurelia-cli/lib/build/bundler.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/bundler'>;
}
declare module 'aurelia-cli/lib/build/concat-with-sourcemaps/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/concat-with-sourcemaps/index'>;
}
declare module 'aurelia-cli/lib/build/convert-source-map/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/convert-source-map/index'>;
}
declare module 'aurelia-cli/lib/build/dependency-description.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/dependency-description'>;
}
declare module 'aurelia-cli/lib/build/dependency-inclusion.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/dependency-inclusion'>;
}
declare module 'aurelia-cli/lib/build/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/index'>;
}
declare module 'aurelia-cli/lib/build/loader-plugin.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/loader-plugin'>;
}
declare module 'aurelia-cli/lib/build/loader.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/loader'>;
}
declare module 'aurelia-cli/lib/build/map-stream/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/map-stream/index'>;
}
declare module 'aurelia-cli/lib/build/package-analyzer.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/package-analyzer'>;
}
declare module 'aurelia-cli/lib/build/source-inclusion.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/source-inclusion'>;
}
declare module 'aurelia-cli/lib/build/utils.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/build/utils'>;
}
declare module 'aurelia-cli/lib/cli-options.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/cli-options'>;
}
declare module 'aurelia-cli/lib/cli.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/cli'>;
}
declare module 'aurelia-cli/lib/colors/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/colors/index'>;
}
declare module 'aurelia-cli/lib/colors/styles.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/colors/styles'>;
}
declare module 'aurelia-cli/lib/colors/supports-colors.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/colors/supports-colors'>;
}
declare module 'aurelia-cli/lib/colors/transform.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/colors/transform'>;
}
declare module 'aurelia-cli/lib/commands/generate/command.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/generate/command'>;
}
declare module 'aurelia-cli/lib/commands/gulp.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/gulp'>;
}
declare module 'aurelia-cli/lib/commands/help/command.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/help/command'>;
}
declare module 'aurelia-cli/lib/commands/import/command.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/import/command'>;
}
declare module 'aurelia-cli/lib/commands/install/command.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/install/command'>;
}
declare module 'aurelia-cli/lib/commands/install/package-argument-parser.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/install/package-argument-parser'>;
}
declare module 'aurelia-cli/lib/commands/new/command.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/command'>;
}
declare module 'aurelia-cli/lib/commands/new/css-processors/less.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/css-processors/less'>;
}
declare module 'aurelia-cli/lib/commands/new/css-processors/none.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/css-processors/none'>;
}
declare module 'aurelia-cli/lib/commands/new/css-processors/postcss.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/css-processors/postcss'>;
}
declare module 'aurelia-cli/lib/commands/new/css-processors/sass.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/css-processors/sass'>;
}
declare module 'aurelia-cli/lib/commands/new/css-processors/stylus.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/css-processors/stylus'>;
}
declare module 'aurelia-cli/lib/commands/new/editors/atom.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/editors/atom'>;
}
declare module 'aurelia-cli/lib/commands/new/editors/none.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/editors/none'>;
}
declare module 'aurelia-cli/lib/commands/new/editors/sublime.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/editors/sublime'>;
}
declare module 'aurelia-cli/lib/commands/new/editors/visualstudio.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/editors/visualstudio'>;
}
declare module 'aurelia-cli/lib/commands/new/editors/vscode.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/editors/vscode'>;
}
declare module 'aurelia-cli/lib/commands/new/editors/webstorm.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/editors/webstorm'>;
}
declare module 'aurelia-cli/lib/commands/new/markup-processors/maximum.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/markup-processors/maximum'>;
}
declare module 'aurelia-cli/lib/commands/new/markup-processors/minimum.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/markup-processors/minimum'>;
}
declare module 'aurelia-cli/lib/commands/new/markup-processors/none.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/markup-processors/none'>;
}
declare module 'aurelia-cli/lib/commands/new/markup-processors/pug.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/markup-processors/pug'>;
}
declare module 'aurelia-cli/lib/commands/new/platforms/aspnetcore.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/platforms/aspnetcore'>;
}
declare module 'aurelia-cli/lib/commands/new/platforms/web.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/platforms/web'>;
}
declare module 'aurelia-cli/lib/commands/new/project-template.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/project-template'>;
}
declare module 'aurelia-cli/lib/commands/new/transpilers/babel.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/transpilers/babel'>;
}
declare module 'aurelia-cli/lib/commands/new/transpilers/typescript.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/transpilers/typescript'>;
}
declare module 'aurelia-cli/lib/commands/new/unit-test-runners/karma.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/unit-test-runners/karma'>;
}
declare module 'aurelia-cli/lib/commands/new/unit-test-runners/none.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/new/unit-test-runners/none'>;
}
declare module 'aurelia-cli/lib/commands/uninstall/command.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/commands/uninstall/command'>;
}
declare module 'aurelia-cli/lib/dependencies.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/dependencies'>;
}
declare module 'aurelia-cli/lib/file-system.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/file-system'>;
}
declare module 'aurelia-cli/lib/importer/import-engine.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/import-engine'>;
}
declare module 'aurelia-cli/lib/importer/package-importer.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/package-importer'>;
}
declare module 'aurelia-cli/lib/importer/package-installer.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/package-installer'>;
}
declare module 'aurelia-cli/lib/importer/package.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/package'>;
}
declare module 'aurelia-cli/lib/importer/services/metadata-service.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/services/metadata-service'>;
}
declare module 'aurelia-cli/lib/importer/services/registry.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/services/registry'>;
}
declare module 'aurelia-cli/lib/importer/services/resource-inclusion.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/services/resource-inclusion'>;
}
declare module 'aurelia-cli/lib/importer/services/tutorial.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/services/tutorial'>;
}
declare module 'aurelia-cli/lib/importer/strategies/amodro.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/strategies/amodro'>;
}
declare module 'aurelia-cli/lib/importer/strategies/aurelia-registry.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/strategies/aurelia-registry'>;
}
declare module 'aurelia-cli/lib/importer/strategies/browser-section.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/strategies/browser-section'>;
}
declare module 'aurelia-cli/lib/importer/strategies/custom-importer.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/strategies/custom-importer'>;
}
declare module 'aurelia-cli/lib/importer/strategies/jspm-section.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/strategies/jspm-section'>;
}
declare module 'aurelia-cli/lib/importer/strategies/metadata.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/strategies/metadata'>;
}
declare module 'aurelia-cli/lib/importer/strategy-loader.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/importer/strategy-loader'>;
}
declare module 'aurelia-cli/lib/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/index'>;
}
declare module 'aurelia-cli/lib/logger.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/logger'>;
}
declare module 'aurelia-cli/lib/mkdirp.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/mkdirp'>;
}
declare module 'aurelia-cli/lib/npm.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/npm'>;
}
declare module 'aurelia-cli/lib/package-managers/npm.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/package-managers/npm'>;
}
declare module 'aurelia-cli/lib/package-managers/yarn.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/package-managers/yarn'>;
}
declare module 'aurelia-cli/lib/project-item.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/project-item'>;
}
declare module 'aurelia-cli/lib/project.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/project'>;
}
declare module 'aurelia-cli/lib/resolve/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resolve/index'>;
}
declare module 'aurelia-cli/lib/resolve/lib/async.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resolve/lib/async'>;
}
declare module 'aurelia-cli/lib/resolve/lib/caller.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resolve/lib/caller'>;
}
declare module 'aurelia-cli/lib/resolve/lib/core.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resolve/lib/core'>;
}
declare module 'aurelia-cli/lib/resolve/lib/node-modules-paths.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resolve/lib/node-modules-paths'>;
}
declare module 'aurelia-cli/lib/resolve/lib/sync.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resolve/lib/sync'>;
}
declare module 'aurelia-cli/lib/resources/content/karma.conf.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/content/karma.conf'>;
}
declare module 'aurelia-cli/lib/resources/environments/dev.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/environments/dev'>;
}
declare module 'aurelia-cli/lib/resources/environments/prod.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/environments/prod'>;
}
declare module 'aurelia-cli/lib/resources/environments/stage.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/environments/stage'>;
}
declare module 'aurelia-cli/lib/resources/generators/attribute.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/generators/attribute'>;
}
declare module 'aurelia-cli/lib/resources/generators/binding-behavior.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/generators/binding-behavior'>;
}
declare module 'aurelia-cli/lib/resources/generators/component.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/generators/component'>;
}
declare module 'aurelia-cli/lib/resources/generators/element.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/generators/element'>;
}
declare module 'aurelia-cli/lib/resources/generators/generator.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/generators/generator'>;
}
declare module 'aurelia-cli/lib/resources/generators/task.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/generators/task'>;
}
declare module 'aurelia-cli/lib/resources/generators/value-converter.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/generators/value-converter'>;
}
declare module 'aurelia-cli/lib/resources/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/index'>;
}
declare module 'aurelia-cli/lib/resources/scripts/configure-bluebird.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/scripts/configure-bluebird'>;
}
declare module 'aurelia-cli/lib/resources/scripts/require.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/scripts/require'>;
}
declare module 'aurelia-cli/lib/resources/scripts/text.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/scripts/text'>;
}
declare module 'aurelia-cli/lib/resources/src/app.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/src/app'>;
}
declare module 'aurelia-cli/lib/resources/src/main.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/src/main'>;
}
declare module 'aurelia-cli/lib/resources/src/resources/index.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/src/resources/index'>;
}
declare module 'aurelia-cli/lib/resources/tasks/build.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/build'>;
}
declare module 'aurelia-cli/lib/resources/tasks/copy-files.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/copy-files'>;
}
declare module 'aurelia-cli/lib/resources/tasks/process-css.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/process-css'>;
}
declare module 'aurelia-cli/lib/resources/tasks/process-less.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/process-less'>;
}
declare module 'aurelia-cli/lib/resources/tasks/process-markup-minify-max.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/process-markup-minify-max'>;
}
declare module 'aurelia-cli/lib/resources/tasks/process-markup-minify-min.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/process-markup-minify-min'>;
}
declare module 'aurelia-cli/lib/resources/tasks/process-markup.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/process-markup'>;
}
declare module 'aurelia-cli/lib/resources/tasks/process-postcss.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/process-postcss'>;
}
declare module 'aurelia-cli/lib/resources/tasks/process-pug.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/process-pug'>;
}
declare module 'aurelia-cli/lib/resources/tasks/process-sass.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/process-sass'>;
}
declare module 'aurelia-cli/lib/resources/tasks/process-stylus.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/process-stylus'>;
}
declare module 'aurelia-cli/lib/resources/tasks/run.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/run'>;
}
declare module 'aurelia-cli/lib/resources/tasks/test.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/test'>;
}
declare module 'aurelia-cli/lib/resources/tasks/transpile.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/tasks/transpile'>;
}
declare module 'aurelia-cli/lib/resources/test/app.spec.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/test/app.spec'>;
}
declare module 'aurelia-cli/lib/resources/test/aurelia-karma.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/test/aurelia-karma'>;
}
declare module 'aurelia-cli/lib/resources/test/setup.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/resources/test/setup'>;
}
declare module 'aurelia-cli/lib/string.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/string'>;
}
declare module 'aurelia-cli/lib/ui.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/ui'>;
}
declare module 'aurelia-cli/lib/workflow/activities/branch-switch.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/workflow/activities/branch-switch'>;
}
declare module 'aurelia-cli/lib/workflow/activities/input-select.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/workflow/activities/input-select'>;
}
declare module 'aurelia-cli/lib/workflow/activities/input-text.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/workflow/activities/input-text'>;
}
declare module 'aurelia-cli/lib/workflow/activities/project-create.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/workflow/activities/project-create'>;
}
declare module 'aurelia-cli/lib/workflow/activities/project-install.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/workflow/activities/project-install'>;
}
declare module 'aurelia-cli/lib/workflow/activities/state-assign.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/workflow/activities/state-assign'>;
}
declare module 'aurelia-cli/lib/workflow/workflow-engine.js' {
  declare module.exports: $Exports<'aurelia-cli/lib/workflow/workflow-engine'>;
}
declare module 'aurelia-cli/spec/helpers/polyfills.js' {
  declare module.exports: $Exports<'aurelia-cli/spec/helpers/polyfills'>;
}
declare module 'aurelia-cli/spec/lib/cli.spec.js' {
  declare module.exports: $Exports<'aurelia-cli/spec/lib/cli.spec'>;
}
declare module 'aurelia-cli/spec/lib/file-system.spec.js' {
  declare module.exports: $Exports<'aurelia-cli/spec/lib/file-system.spec'>;
}
declare module 'aurelia-cli/spec/lib/project-item.spec.js' {
  declare module.exports: $Exports<'aurelia-cli/spec/lib/project-item.spec'>;
}
declare module 'aurelia-cli/spec/lib/project.spec.js' {
  declare module.exports: $Exports<'aurelia-cli/spec/lib/project.spec'>;
}
