// flow-typed signature: e58ba8dfc62c66b4830d94dff1986824
// flow-typed version: <<STUB>>/bootstrap-css-only_v^3.3.7/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-css-only'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-css-only' {
  declare module.exports: any;
}
