// flow-typed signature: 9636a12cc4da1a3d7b117bf781a7cc87
// flow-typed version: <<STUB>>/bytes_v^2.5.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bytes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bytes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bytes/index' {
  declare module.exports: $Exports<'bytes'>;
}
declare module 'bytes/index.js' {
  declare module.exports: $Exports<'bytes'>;
}
