// flow-typed signature: 2f535e1ba03d4ae37681fef1f9973ab3
// flow-typed version: <<STUB>>/dev-ip_v^1.0.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dev-ip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dev-ip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dev-ip/example' {
  declare module.exports: any;
}

declare module 'dev-ip/lib/dev-ip' {
  declare module.exports: any;
}

declare module 'dev-ip/test/devip' {
  declare module.exports: any;
}

declare module 'dev-ip/test/fixtures/resp-multiple' {
  declare module.exports: any;
}

declare module 'dev-ip/test/fixtures/resp-none' {
  declare module.exports: any;
}

declare module 'dev-ip/test/fixtures/resp-single' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dev-ip/example.js' {
  declare module.exports: $Exports<'dev-ip/example'>;
}
declare module 'dev-ip/lib/dev-ip.js' {
  declare module.exports: $Exports<'dev-ip/lib/dev-ip'>;
}
declare module 'dev-ip/test/devip.js' {
  declare module.exports: $Exports<'dev-ip/test/devip'>;
}
declare module 'dev-ip/test/fixtures/resp-multiple.js' {
  declare module.exports: $Exports<'dev-ip/test/fixtures/resp-multiple'>;
}
declare module 'dev-ip/test/fixtures/resp-none.js' {
  declare module.exports: $Exports<'dev-ip/test/fixtures/resp-none'>;
}
declare module 'dev-ip/test/fixtures/resp-single.js' {
  declare module.exports: $Exports<'dev-ip/test/fixtures/resp-single'>;
}
