// flow-typed signature: 3de9ddf1336b9b7d7474ebb6678ab22f
// flow-typed version: <<STUB>>/easy-extender_v^2.3.2/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'easy-extender'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'easy-extender' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'easy-extender/index' {
  declare module.exports: $Exports<'easy-extender'>;
}
declare module 'easy-extender/index.js' {
  declare module.exports: $Exports<'easy-extender'>;
}
