// flow-typed signature: bbe1850e50729f30cbf12088b22ebdac
// flow-typed version: <<STUB>>/eazy-logger_v^3.0.2/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eazy-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eazy-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eazy-logger/example' {
  declare module.exports: any;
}

declare module 'eazy-logger/lodash.custom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eazy-logger/example.js' {
  declare module.exports: $Exports<'eazy-logger/example'>;
}
declare module 'eazy-logger/index' {
  declare module.exports: $Exports<'eazy-logger'>;
}
declare module 'eazy-logger/index.js' {
  declare module.exports: $Exports<'eazy-logger'>;
}
declare module 'eazy-logger/lodash.custom.js' {
  declare module.exports: $Exports<'eazy-logger/lodash.custom'>;
}
