// flow-typed signature: 4c27952ab3336b0ed4d796413b0ccbe1
// flow-typed version: <<STUB>>/gulp-htmlmin_v^3.0.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-htmlmin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-htmlmin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-htmlmin/index' {
  declare module.exports: $Exports<'gulp-htmlmin'>;
}
declare module 'gulp-htmlmin/index.js' {
  declare module.exports: $Exports<'gulp-htmlmin'>;
}
