// flow-typed signature: b45ea779f0ffc01110f5902942e5853b
// flow-typed version: <<STUB>>/gulp-autoprefixer_v^4.0.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-autoprefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-autoprefixer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-autoprefixer/index' {
  declare module.exports: $Exports<'gulp-autoprefixer'>;
}
declare module 'gulp-autoprefixer/index.js' {
  declare module.exports: $Exports<'gulp-autoprefixer'>;
}
