// flow-typed signature: 25b94431c439d1bb6d344ad761375790
// flow-typed version: <<STUB>>/gulp-changed-in-place_v^2.0.3/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-changed-in-place'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-changed-in-place' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-changed-in-place/index' {
  declare module.exports: $Exports<'gulp-changed-in-place'>;
}
declare module 'gulp-changed-in-place/index.js' {
  declare module.exports: $Exports<'gulp-changed-in-place'>;
}
