// flow-typed signature: 3812617f17f0cd438f9675419747f412
// flow-typed version: <<STUB>>/har-schema_v^2.0.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'har-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'har-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'har-schema/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'har-schema/lib/index.js' {
  declare module.exports: $Exports<'har-schema/lib/index'>;
}
