// flow-typed signature: 60f0a1245df51676a07b364ea7fc0a9d
// flow-typed version: <<STUB>>/ms_v^2.0.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ms/index' {
  declare module.exports: $Exports<'ms'>;
}
declare module 'ms/index.js' {
  declare module.exports: $Exports<'ms'>;
}
