// flow-typed signature: 6dda6f67cbe1bb11881fb19393834e7c
// flow-typed version: <<STUB>>/pseudomap_v^1.0.2/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pseudomap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pseudomap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pseudomap/map' {
  declare module.exports: any;
}

declare module 'pseudomap/pseudomap' {
  declare module.exports: any;
}

declare module 'pseudomap/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pseudomap/map.js' {
  declare module.exports: $Exports<'pseudomap/map'>;
}
declare module 'pseudomap/pseudomap.js' {
  declare module.exports: $Exports<'pseudomap/pseudomap'>;
}
declare module 'pseudomap/test/basic.js' {
  declare module.exports: $Exports<'pseudomap/test/basic'>;
}
