// flow-typed signature: 1d7639a022612fcf839d456aacc2892a
// flow-typed version: <<STUB>>/resp-modifier_v^6.0.2/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resp-modifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resp-modifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resp-modifier/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resp-modifier/index' {
  declare module.exports: $Exports<'resp-modifier'>;
}
declare module 'resp-modifier/index.js' {
  declare module.exports: $Exports<'resp-modifier'>;
}
declare module 'resp-modifier/lib/utils.js' {
  declare module.exports: $Exports<'resp-modifier/lib/utils'>;
}
