// flow-typed signature: 777e57dc7c11fac556b7ee9395826f58
// flow-typed version: <<STUB>>/text_vgithub:requirejs/text#latest/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'text/text' {
  declare module.exports: any;
}

// Filename aliases
declare module 'text/text.js' {
  declare module.exports: $Exports<'text/text'>;
}
