// flow-typed signature: 516b75ef288c467c565825cb738cf247
// flow-typed version: <<STUB>>/yallist_v^3.0.2/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yallist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yallist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yallist/iterator' {
  declare module.exports: any;
}

declare module 'yallist/yallist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yallist/iterator.js' {
  declare module.exports: $Exports<'yallist/iterator'>;
}
declare module 'yallist/yallist.js' {
  declare module.exports: $Exports<'yallist/yallist'>;
}
